export interface VinylRecord {
  id: string; // generated by us, must be unique
  'Catalog#': string;
  Artist: string;
  Title: string;
  Label?: string[]; // May be comma-separated in CSV, normalize to array
  Format?: string[]; // Normalize to array
  Rating?: number; // Often NaN or missing
  Released?: number; // NaN/missing means undefined
  release_id?: number; // Discogs-specific ID
  Notes?: string; // Wantlist only
  Genres: string[]; // added manually by us
  'Primary Genre': string; // added by us based on first genre
  'Image url': string; // added manually by us

  // Collection-only fields
  CollectionFolder?: string;
  'Date Added'?: string; // ISO format datetime
  'Collection Media Condition'?: string;
  'Collection Sleeve Condition'?: string;
  'Collection Originally from'?: string;
  'Collection Notes'?: string;

  // Catch-all for unknown extra Discogs fields
  [key: string]: any;
}

export interface LogEntry {
  message: string;
  type: 'info' | 'success' | 'error' | 'warning';
}